---
title: "Tema 6 - Espacios vectoriales"
author: "Ramon Ceballos"
date: "11/3/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **Bases ortogonales y ortonormales**

# 1. Bases ortogonales

<l class = "definition">**Base ortogonal.**</l> Dada una base $B = \{\vec{u}_1,\vec{u}_2,\dots,\vec{u}_n\}$ de un espacio vectorial $E$, se dice que se trata de una base ortogonal si sus elementos son ortogonales dos a dos (el producto escalar da 0). Matemáticamente:

$$\langle\vec{u}_i,\vec{u}_j\rangle = 0\quad\forall i\ne j$$

# 2. Bases ortonormales

<l class = "definition">**Base ortonormal.**</l> Dada una base $B = \{\vec{u}_1,\vec{u}_2,\dots,\vec{u}_n\}$ de un espacio vectorial $E$, se dice que se trata de una base ortonormal si es ortogonal y todos sus elementos son unitarios. Matemáticamente:

$$\langle\vec{u}_i,\vec{u}_j\rangle = 0\quad\forall i\ne j$$
$$||\vec{u}_i|| = 1\quad\forall i$$

# 3. Método de ortogonalización de Gram-Schmidt

<l class = "definition">**Método de ortogonalización de Gram-Schmidt.**</l> Permite construir una base ortogonal a partir de una base cualquiera del espacio vectorial.

## 3.1 Demostración

**Método de ortogonalización de Gram-Schmidt**

Sea $B= \{\vec{v}_1,\vec{v}_2,\dots,\vec{v}_n\}$ una base cualquiera de un espacio vectorial $E$ de $\dim(E) = n$.

A partir de los vectores de la base $B$, se construirá una nueva base $B_o = \{\vec{u}_1,\vec{u}_2,\dots,\vec{u}_n\}$ que será ortogonal y del mismo espacio.

1. Se toma $\vec{u}_1 =\vec{v}_1$ como primer vetor de la base nueva.

2. El segundo vector será una combinación lineal de $\vec{v}_1$ y $\vec{v}_2$ de la forma $\vec{u}_2 = \vec{v}_2-\alpha\vec{u}_1$, al cual se le impondrá la condición de que debe ser perpendicular a $\vec{u}_1$. Es decir, $\vec{u}_1\perp\vec{u}_2$. De este modo obtendremos:

$$\alpha = \frac{\langle\vec{u}_1,\vec{v}_2\rangle}{\langle\vec{u}_1,\vec{u}_1\rangle}\Rightarrow \vec{u}_2 = \vec{v}_2-\frac{\langle\vec{u}_1,\vec{v}_2\rangle}{\langle\vec{u}_1,\vec{u}_1\rangle}\vec{v_1}$$

3. Para calcular el tercer vector, se procede del mismo modo: el tercer vector será una combinación lineal de $\vec{v}_1,\vec{v}_2,\vec{v}_3$ de la forma $\vec{u}_3= \vec{v}_3-\alpha_1\vec{u_1}-\alpha_2\vec{u}_2$ a la cual se impondrán las condiciones $\vec{u}_1\perp\vec{u}_3$ y $\vec{u}_2\perp\vec{u}_3$. Operando se obtniene:

$$\alpha_1 = \frac{\langle\vec{u}_1,\vec{v}_3\rangle}{\langle\vec{u}_1,\vec{u}_1\rangle};\quad\alpha_2 = \frac{\langle\vec{u}_2,\vec{v}_3\rangle}{\langle\vec{u}_2,\vec{u}_2\rangle}$$ $$\vec{u}_3 = \vec{v}_3-\frac{\langle\vec{u}_1,\vec{v}_3\rangle}{\langle\vec{u}_1,\vec{u}_1\rangle}\vec{u}_1-\frac{\langle\vec{u}_2,\vec{v}_3\rangle}{\langle\vec{u}_2,\vec{u}_2\rangle}\vec{u}_2$$


4. Y operamos de forma análoga hasta llegar al último vector de la base, obteniendo la expresión:

$$\vec{u}_n = \vec{v}_n-\sum_{i=1}^{n-1}\frac{\langle\vec{u}_i,\vec{v}_n\rangle}{\langle\vec{u}_i,\vec{u}_i\rangle}\vec{u}_i$$

5. Finalmente, si lo que se quiere es una base ortonormal, bastará con dividir cada vector por su norma para así normalizar todos los elementos de la base.


# 4. Proyección ortogonal de un vector sobre un subespacio vectorial

<l class = "definition">**Vector ortogonal a un subespacio.**</l> Un vector $\vec{u}\in E$ es ortogonal a un subespacio vectorial $S\subseteq E$ si, y solo si se cumple que:

$$\langle\vec{u},\vec{x}\rangle = 0\quad\forall\vec{x}\in S$$

Siendo $\vec{x}$ cada uno de los vectores que forman el subespacio vectorial $S$; y $U$ sería un vector del espacio vectorial $E$.

## 4.1 Ortogonalidad de un vector con un subespacio

<l class = "prop">**Teorema.**</l> Un vector $\vec{u}\in E$ es ortogonal a un subespacio vectorial $S\subseteq E$ si, y solo si, es ortogonal a todos los vectores de una base de $S$.

## 4.2 Ortogonalidad de dos subespacios del mismo espacio vectorial

Este concepto se puede extender a un nivel más elevado.

<l class = "prop">**Teorema.**</l> Dos subespacio vectoriales $V$ y $W$ de $E$ son ortogonales si se cumple:

$$\forall\vec{x}\in V,\ \forall\vec{y}\in W\Rightarrow \langle\vec{x},\vec{y}\rangle = 0$$

<l class = "prop">**Teorema.**</l> Para que dos subespacios $V$ y $W$ sean ortogonales, es suficiente con que los vectores de una base de $V$ sean ortogonales a los vectores de una base de $W$.

## 4.3 Proyección ortogonal de un vector sobre un subespacio

Recordemos...

<l class = "definition">**Proyección ortogonal.**</l> La proyección ortogonal de un vector $\vec{u}$ sobre otro $\vec{v}$, se expresa como:

$$P_{\vec{u}}(\vec{v}) = \frac{\langle\vec{u},\vec{v}\rangle}{\langle\vec{v},\vec{v}\rangle}\vec{v} = \frac{\langle\vec{u},\vec{v}\rangle}{||\vec{v}||^2}\vec{v} $$

<l class = "definition">**Proyección ortogonal de un vector sobre un subespacio.**</l> Dado $S$ un subespacio vectorial de un espacio vectorial $E$, todo vector $\vec{u}\in E$ se descompone de manera única en:

$$\vec{u} = \vec{u}_S+\vec{u}_0$$

Con $\vec{u}_S\in S$ y $\vec{u}_0\in S^{\perp}$ (subespacio ortogonal de S). En particular, el vector $\vec{u}_S\in S$ se denomina <l class = "definition">**vector proyección ortogonal**</l> de $\vec{u}$ sobre $S$.


<l class = "definition">**Proyección ortogonal de un vector sobre un subespacio.**</l> Si se toma en $S$ una base ortogonal $\{\vec{s}_1,\vec{s}_2,\dots,\vec{s}_r\}$, la proyección de $\vec{u}$ sobre $S$ viene dada por:

$$P_{S}(\vec{u}) = \vec{u}_S = \sum_{i = 1}^r\frac{\langle\vec{u},\vec{s}_i\rangle}{||\vec{s}_i||^2}\vec{s}_i$$







