theme: jekyll-theme-cayman
title: Curso completo de álgebra lineal con R, Python y Octave
description: Aprende las bases para aplicar el álgebra lineal a la Estadística, al Machine Learning y la Inteligencia Artificial para ser un experto en el campo.
url: https://www.udemy.com/course/algebralineal/?referralCode=219A2DBFEE5DEE180914